/**
 * داده‌های اولیه مراجع و قواعد فقهی
 *
 * ⚠️ این داده‌ها جنبه کمک‌آموزشی دارند و باید پیش از انتشار
 * توسط دفاتر مراجع محترم تأیید شوند (verified_by_office = true).
 */

const marjas = [
  {
    id: 'khamenei',
    name: 'آیت‌الله خامنه‌ای',
    name_ar: 'آية الله الخامنئي',
    name_en: 'Ayatollah Khamenei',
    website_url: 'https://www.leader.ir',
    office_phone: '+982133200000',
    offices: JSON.stringify(['تهران', 'قم', 'مشهد', 'اصفهان', 'شیراز']),
    rules: JSON.stringify({
      paymentPolicy: 'toMarjaOffice',
      emergencySavingsExempt: true,
      futureNecessitiesSavingsExempt: false,
      trousseauExempt: false,
      gradualTrousseauExempt: false,
      sayyidShareDirectPayment: false,
      imamShareRequiresPermission: true,
      capitalBoughtFromUnkhumsedIncome: true,
      medicalExpensesDeductible: true,
      debtsDeductible: true,
      inheritanceExempt: true,
      dowryExempt: true,
      bloodMoneyExempt: true,
      khumsRate: 0.2,
      imamShareRatio: 0.5,
      sayyidShareRatio: 0.5,
      note: 'خمس باید به دفتر یا وکیل مرجع پرداخت شود. پس‌انداز برای پیشامدها (با شرایط) معاف است.',
      disclaimer: null,
    }),
    rules_version: 1,
    verified_by_office: false,
  },
  {
    id: 'sistani',
    name: 'آیت‌الله سیستانی',
    name_ar: 'آية الله السيستاني',
    name_en: 'Ayatollah Sistani',
    website_url: 'https://www.sistani.org',
    office_phone: '+964313000000',
    offices: JSON.stringify(['نجف', 'قم', 'مشهد', 'تهران']),
    rules: JSON.stringify({
      paymentPolicy: 'sayyidDirectImamPermission',
      emergencySavingsExempt: false,
      futureNecessitiesSavingsExempt: false,
      trousseauExempt: false,
      gradualTrousseauExempt: false,
      sayyidShareDirectPayment: true,
      imamShareRequiresPermission: true,
      capitalBoughtFromUnkhumsedIncome: true,
      medicalExpensesDeductible: true,
      debtsDeductible: true,
      inheritanceExempt: true,
      dowryExempt: true,
      bloodMoneyExempt: true,
      khumsRate: 0.2,
      imamShareRatio: 0.5,
      sayyidShareRatio: 0.5,
      note: 'سهم سادات را می‌توان مستقیم پرداخت کرد؛ سهم امام نیاز به اجازه دارد.',
      disclaimer: null,
    }),
    rules_version: 1,
    verified_by_office: false,
  },
  {
    id: 'makarem',
    name: 'آیت‌الله مکارم شیرازی',
    name_ar: 'آية الله مكارم الشيرازي',
    name_en: 'Ayatollah Makarem Shirazi',
    website_url: 'https://www.makarem.ir',
    office_phone: '+982513000000',
    offices: JSON.stringify(['قم', 'شیراز', 'مشهد']),
    rules: JSON.stringify({
      paymentPolicy: 'freePayment',
      emergencySavingsExempt: false,
      futureNecessitiesSavingsExempt: false,
      trousseauExempt: true,
      gradualTrousseauExempt: true,
      sayyidShareDirectPayment: false,
      imamShareRequiresPermission: true,
      capitalBoughtFromUnkhumsedIncome: true,
      medicalExpensesDeductible: true,
      debtsDeductible: true,
      inheritanceExempt: true,
      dowryExempt: true,
      bloodMoneyExempt: true,
      khumsRate: 0.2,
      imamShareRatio: 0.5,
      sayyidShareRatio: 0.5,
      note: 'در شهرهای متعارف، تهیه تدریجی جهیزیه معاف است.',
      disclaimer: null,
    }),
    rules_version: 1,
    verified_by_office: false,
  },
  {
    id: 'shobeiri',
    name: 'آیت‌الله شبیری زنجانی',
    name_ar: 'آية الله الشبیری الزنجاني',
    name_en: 'Ayatollah Shobeiri Zanjani',
    website_url: 'https://www.zanjani.ir',
    office_phone: '+982512000000',
    offices: JSON.stringify(['قم', 'زنجان']),
    rules: JSON.stringify({
      paymentPolicy: 'freePayment',
      emergencySavingsExempt: false,
      futureNecessitiesSavingsExempt: true,
      trousseauExempt: false,
      gradualTrousseauExempt: false,
      sayyidShareDirectPayment: false,
      imamShareRequiresPermission: true,
      capitalBoughtFromUnkhumsedIncome: true,
      medicalExpensesDeductible: true,
      debtsDeductible: true,
      inheritanceExempt: true,
      dowryExempt: true,
      bloodMoneyExempt: true,
      khumsRate: 0.2,
      imamShareRatio: 0.5,
      sayyidShareRatio: 0.5,
      note: 'پس‌انداز برای هزینه‌های ضروری آینده معاف است.',
      disclaimer: null,
    }),
    rules_version: 1,
    verified_by_office: false,
  },
  {
    id: 'noori',
    name: 'آیت‌الله نوری همدانی',
    name_ar: 'آية الله النوري الهمداني',
    name_en: 'Ayatollah Noori Hamedani',
    website_url: 'https://www.noorihamedani.ir',
    office_phone: '+982511000000',
    offices: JSON.stringify(['قم', 'همدان']),
    rules: JSON.stringify({
      paymentPolicy: 'freePayment',
      emergencySavingsExempt: false,
      futureNecessitiesSavingsExempt: false,
      trousseauExempt: false,
      gradualTrousseauExempt: false,
      sayyidShareDirectPayment: false,
      imamShareRequiresPermission: true,
      capitalBoughtFromUnkhumsedIncome: true,
      medicalExpensesDeductible: true,
      debtsDeductible: true,
      inheritanceExempt: true,
      dowryExempt: true,
      bloodMoneyExempt: true,
      khumsRate: 0.2,
      imamShareRatio: 0.5,
      sayyidShareRatio: 0.5,
      note: 'برای پرداخت خمس با دفتر مرجع مشورت کنید.',
      disclaimer: null,
    }),
    rules_version: 1,
    verified_by_office: false,
  },
];

exports.seed = async function seed(knex) {
  await knex('marjas').del();
  await knex('marjas').insert(marjas);
};
